name: Build and Release

on:
  push:
    branches: [ forge-1.20.1, main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ forge-1.20.1, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs/*.jar
    
    # Create release if this is a tag push
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: AstroExpansion ${{ github.ref }}
        body: |
          ## AstroExpansion Release
          
          This release was automatically generated from tag ${{ github.ref }}.
          
          ### Installation
          1. Install Minecraft Forge 1.20.1 (version 47.2.0 or newer)
          2. Download the JAR file below
          3. Place it in your `.minecraft/mods` folder
          
          ### What's New
          See [RELEASE_NOTES.md](https://github.com/${{ github.repository }}/blob/${{ github.ref }}/RELEASE_NOTES_${{ github.ref }}.md) for details.
        draft: false
        prerelease: false
    
    - name: Get JAR filename
      if: startsWith(github.ref, 'refs/tags/v')
      id: get_filename
      run: |
        JAR_FILE=$(ls build/libs/*.jar | grep -v sources | head -1)
        echo "JAR_FILE=$JAR_FILE" >> $GITHUB_OUTPUT
        echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_OUTPUT
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.get_filename.outputs.JAR_FILE }}
        asset_name: astroexpansion-${{ github.ref_name }}-mc1.20.1.jar
        asset_content_type: application/java-archive